# Screen settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Grid settings
GRID_SIZE = 10
GRID_WIDTH = SCREEN_WIDTH // GRID_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // GRID_SIZE
CELL_SIZE=10

# FPS
FPS_LIMIT = 60  # Maximum frames per second